### PR TITLE
Improved nrnl.sh

### PR DESCRIPTION
**Pull request by ghost**
- Implemented the script in ```bash``` instead of ```fish``` for better portability.
- Added an algorithm that allows easy formatting in ANSI escape codes.
  - ANSI escape codes have been related to base 16 colors.
  - Usage: Wrapping text in ```$f1``` and ```$rst``` will change foreground color to red.
- No assumptions are made for *os*, *wm* and *init* variables. They are detected using ```coreutils``` and ```xprop```.
- Output using *here document* (```cat <<EOF```).

Tell me if it works or not.
I really like your concepts. Pardon me for stealing almost everything from you for my ricing.
Thanks.

### CODE REVIEW

**Comment by ghost** [comment]
I made a slight mistake in the *commit message*. (```cat <<<EOF``` instead of ```cat <<EOF```)

**Review by ghost — COMMENTED** [review]
damn i make a lot of mistakes

**Comment by eti0** [comment]
hey that's pretty cool thanks for that

though i'm having issues with the output of the distro's name (see pic below)


know where that might come from?

**Comment by eti0** [comment]
now that i think of it it could just be replaced by a simple `source /etc/os-release && echo $NAME`


don't really know if that's the correct way to do it but oh well

**Comment by ghost** [comment]
does this look familiar?
final

**Comment by eti0** [comment]
not sure I like the color blocks but hey you can always add an argument to enable them or not I guess
cool work anyway man

i'm also not sure that the kernel shortening works, i might be wrong though, what were you trying to do [here](https://github.com/eti0/dots/commit/ee23d9c1c69d66e35a042ef241e067b6d84a2fa6#diff-82020cd7e778bb6902bf56a20a686071R19)?

**Comment by ghost** [comment]
my kernel output contained ```ARCH``` at the end. it looks out of place so i added a parameter expansion to remove text after final hyphen

**Comment by ghost** [comment]
added parameter ```-b``` for blocks

**Comment by ghost** [comment]
are you getting errors with the kernel shortening?

**Comment by eti0** [comment]
everything is working fine :)


do you want me to merge now or do you want to add more stuff to it?

**Comment by ghost** [comment]
merge? :D
remember you can change colors by replacing ```f1``` with:
- ```f0``` for black
- ```f1``` for red
- ```f2``` for green
- and so on...

**Comment by eti0** [comment]
yeah i guessed that's how it works ^^
thanks a lot for everything, you rock dude

**Comment by ghost** [comment]
i learned a lot doing this :)

**Comment by ghost** [comment]
hey i found that line ```23``` and ```24``` are of no use
you should remove them

**Comment by eti0** [comment]
just removed them, thanks!

**Pull request merged**
